# Stage 1: Build the Angular application
FROM node:22.12.0 AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install -g @angular/cli@19.0.6
RUN npm install
COPY . .
RUN ng build -c production --delete-output-path
# Stage 2: Serve
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
COPY --from=build /app/dist/panel /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
