services:
  server:
    build:
      context: .
      dockerfile: server/dockerfile
    container_name: ${APP_NAME}-server
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./server:/app
    networks:
      - flowize
    depends_on:
      - "postgres"
      - "redis"
      - "hasura"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  client:
    build:
      context: .
      dockerfile: client/dockerfile
    container_name: ${APP_NAME}-client
    restart: always
    ports:
      - "${CLIENT_PORT}:4200"
    volumes:
      - ./client:/app
    networks:
      - flowize
    depends_on:
      - "server"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  hasura:
    image: hasura/graphql-engine:v2.9.0
    container_name: ${APP_NAME}-hasura
    restart: always
    ports:
      - "${HASURA_PORT}:8080"
    volumes:
      - ./server:/hasura-migrations
    networks:
      - flowize
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${DB_USER}:${DB_PASS}@${APP_NAME}-postgres:${DB_PORT}/${DB_NAME}"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"${JWT_SECRET}"}'
    depends_on:
      - "postgres"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}-postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - flowize
    environment:
      - TZ="Europe/Istanbul"
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  redis:
    image: redis:latest
    container_name: ${APP_NAME}-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - flowize
networks:
  flowize:
    driver: bridge
volumes:
  db: